name: Build and Publish to Docker
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk:15
    steps:
      - uses: actions/checkout@master

      - name: Build project with Maven
        run: mvn package

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: borysserbyn/springtest
          tag_with_ref: true
          tag_with_sha: true
